//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_articles
    {
        public TB_articles()
        {
            this.TB_stock = new HashSet<TB_stock>();
            this.TB_lot_entrestock = new HashSet<TB_lot_entrestock>();
        }
    
        public int Id_articles { get; set; }
        public string Nom_articles { get; set; }
        public Nullable<int> Qte_alerte { get; set; }
        public string Description { get; set; }
        public Nullable<int> Id_categorie { get; set; }
        public Nullable<System.DateTime> DateCreer { get; set; }
        public string CreerPar { get; set; }
    
        public virtual TB_categorie TB_categorie { get; set; }
        public virtual ICollection<TB_stock> TB_stock { get; set; }
        public virtual ICollection<TB_lot_entrestock> TB_lot_entrestock { get; set; }
    }
}
