//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_bonSortie_stock
    {
        public int Id_bon_sortiestock { get; set; }
        public string Description { get; set; }
        public Nullable<int> Id_employe { get; set; }
        public Nullable<System.DateTime> Date_sortie { get; set; }
        public Nullable<System.DateTime> DateCreer { get; set; }
        public string CreerPar { get; set; }
    }
}
