//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_bonEntre
    {
        public TB_bonEntre()
        {
            this.TB_lot_entrestock = new HashSet<TB_lot_entrestock>();
        }
    
        public int Id_bon_entrestock { get; set; }
        public Nullable<System.DateTime> Date_entre { get; set; }
        public string Description { get; set; }
        public Nullable<int> Id_livraison { get; set; }
        public Nullable<System.DateTime> DateCreer { get; set; }
        public string CreerPar { get; set; }
    
        public virtual TB_livraison TB_livraison { get; set; }
        public virtual ICollection<TB_lot_entrestock> TB_lot_entrestock { get; set; }
    }
}
