//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_bonRequisition
    {
        public int Id_bon_requisition { get; set; }
        public string Description { get; set; }
        public string aprouvepar { get; set; }
        public Nullable<int> Id_emloye { get; set; }
        public Nullable<System.DateTime> Date_requisition { get; set; }
        public Nullable<System.DateTime> DateCeer { get; set; }
        public string CreerPar { get; set; }
    }
}
