//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_categorie
    {
        public TB_categorie()
        {
            this.TB_articles = new HashSet<TB_articles>();
        }
    
        public int Id_categorie { get; set; }
        public string Nom_categorie { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> DateCreer { get; set; }
        public string CreerPar { get; set; }
    
        public virtual ICollection<TB_articles> TB_articles { get; set; }
    }
}
