//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_detail_sortie
    {
        public int Id_details_sortie { get; set; }
        public Nullable<int> Id_bonsortie { get; set; }
        public Nullable<int> Id_lot_entrestock { get; set; }
        public Nullable<int> Quantite { get; set; }
    }
}
