//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_livraison
    {
        public TB_livraison()
        {
            this.TB_bonEntre = new HashSet<TB_bonEntre>();
        }
    
        public int Id_livraison { get; set; }
        public string Code_fiche { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Image_fiche { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> DateCreer { get; set; }
        public string CreerPar { get; set; }
        public string ImageUrl { get; set; }
    
        public virtual ICollection<TB_bonEntre> TB_bonEntre { get; set; }
    }
}
