//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_lot_entrestock
    {
        public int Id_lot_entrestock { get; set; }
        public Nullable<System.DateTime> Date_entrer { get; set; }
        public Nullable<int> Id_articles { get; set; }
        public Nullable<int> Id_bon_entrestock { get; set; }
        public Nullable<int> Quantite { get; set; }
        public Nullable<long> Total { get; set; }
    
        public virtual TB_articles TB_articles { get; set; }
        public virtual TB_bonEntre TB_bonEntre { get; set; }
    }
}
