//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_stock
    {
        public int Id_stock { get; set; }
        public Nullable<int> Stock_initial { get; set; }
        public int Qte_entre { get; set; }
        public Nullable<int> Qte_sortie { get; set; }
        public Nullable<int> Qte_reste { get; set; }
        public Nullable<int> Id_articles { get; set; }
        public Nullable<System.DateTime> DateCreer { get; set; }
        public string CreerPar { get; set; }
    
        public virtual TB_articles TB_articles { get; set; }
    }
}
